/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GolferRouteImport } from './routes/golfer'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ClubRouteImport } from './routes/club'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GolferIndexRouteImport } from './routes/golfer.index'
import { Route as ClubIndexRouteImport } from './routes/club.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as GolferWalletRouteImport } from './routes/golfer.wallet'
import { Route as GolferScorecardRouteImport } from './routes/golfer.scorecard'
import { Route as GolferProfileRouteImport } from './routes/golfer.profile'
import { Route as GolferLoyaltyRouteImport } from './routes/golfer.loyalty'
import { Route as ClubVouchersRouteImport } from './routes/club.vouchers'
import { Route as ClubSlotsRouteImport } from './routes/club.slots'
import { Route as ClubPromotionsRouteImport } from './routes/club.promotions'
import { Route as ClubLoyaltyRouteImport } from './routes/club.loyalty'
import { Route as ClubCourseSetupRouteImport } from './routes/club.course-setup'
import { Route as ClubBookinglistRouteImport } from './routes/club.bookinglist'
import { Route as ClubAnalyticsRouteImport } from './routes/club.analytics'
import { Route as AppWalletRouteImport } from './routes/app.wallet'
import { Route as AppScorecardRouteImport } from './routes/app.scorecard'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppLoyaltyRouteImport } from './routes/app.loyalty'
import { Route as AppLoginRouteImport } from './routes/app.login'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminClubAdminsRouteImport } from './routes/admin.club-admins'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAppsRouteImport } from './routes/admin.apps'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as GolferTournamentsIndexRouteImport } from './routes/golfer.tournaments.index'
import { Route as GolferCoursesIndexRouteImport } from './routes/golfer.courses.index'
import { Route as GolferBookingsIndexRouteImport } from './routes/golfer.bookings.index'
import { Route as ClubMembersIndexRouteImport } from './routes/club.members.index'
import { Route as AppTournamentsIndexRouteImport } from './routes/app.tournaments.index'
import { Route as AppCoursesIndexRouteImport } from './routes/app.courses.index'
import { Route as AppBookingsIndexRouteImport } from './routes/app.bookings.index'
import { Route as AdminMembersIndexRouteImport } from './routes/admin.members.index'
import { Route as TournamentsTournamentIdLiveRouteImport } from './routes/tournaments.$tournamentId.live'
import { Route as GolferTournamentsTournamentIdRouteImport } from './routes/golfer.tournaments.$tournamentId'
import { Route as GolferHistoryClubIdRouteImport } from './routes/golfer.history.$clubId'
import { Route as GolferCoursesCourseIdRouteImport } from './routes/golfer.courses.$courseId'
import { Route as GolferBookingsBookingIdRouteImport } from './routes/golfer.bookings.$bookingId'
import { Route as GolferBookCourseIdRouteImport } from './routes/golfer.book.$courseId'
import { Route as ClubMembersMemberIdRouteImport } from './routes/club.members.$memberId'
import { Route as AppTournamentsTournamentIdRouteImport } from './routes/app.tournaments.$tournamentId'
import { Route as AppHistoryClubIdRouteImport } from './routes/app.history.$clubId'
import { Route as AppCoursesCourseIdRouteImport } from './routes/app.courses.$courseId'
import { Route as AppBookingsBookingIdRouteImport } from './routes/app.bookings.$bookingId'
import { Route as AppBookCourseIdRouteImport } from './routes/app.book.$courseId'
import { Route as AdminMembersUserIdRouteImport } from './routes/admin.members.$userId'
import { Route as GolferTournamentsTournamentIdScoreRouteImport } from './routes/golfer.tournaments.$tournamentId.score'
import { Route as AppTournamentsTournamentIdScoreRouteImport } from './routes/app.tournaments.$tournamentId.score'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GolferRoute = GolferRouteImport.update({
  id: '/golfer',
  path: '/golfer',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GolferIndexRoute = GolferIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GolferRoute,
} as any)
const ClubIndexRoute = ClubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClubRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const GolferWalletRoute = GolferWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => GolferRoute,
} as any)
const GolferScorecardRoute = GolferScorecardRouteImport.update({
  id: '/scorecard',
  path: '/scorecard',
  getParentRoute: () => GolferRoute,
} as any)
const GolferProfileRoute = GolferProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => GolferRoute,
} as any)
const GolferLoyaltyRoute = GolferLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => GolferRoute,
} as any)
const ClubVouchersRoute = ClubVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => ClubRoute,
} as any)
const ClubSlotsRoute = ClubSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => ClubRoute,
} as any)
const ClubPromotionsRoute = ClubPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => ClubRoute,
} as any)
const ClubLoyaltyRoute = ClubLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => ClubRoute,
} as any)
const ClubCourseSetupRoute = ClubCourseSetupRouteImport.update({
  id: '/course-setup',
  path: '/course-setup',
  getParentRoute: () => ClubRoute,
} as any)
const ClubBookinglistRoute = ClubBookinglistRouteImport.update({
  id: '/bookinglist',
  path: '/bookinglist',
  getParentRoute: () => ClubRoute,
} as any)
const ClubAnalyticsRoute = ClubAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ClubRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppScorecardRoute = AppScorecardRouteImport.update({
  id: '/scorecard',
  path: '/scorecard',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLoyaltyRoute = AppLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClubAdminsRoute = AdminClubAdminsRouteImport.update({
  id: '/club-admins',
  path: '/club-admins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppsRoute = AdminAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const GolferTournamentsIndexRoute = GolferTournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => GolferRoute,
} as any)
const GolferCoursesIndexRoute = GolferCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => GolferRoute,
} as any)
const GolferBookingsIndexRoute = GolferBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => GolferRoute,
} as any)
const ClubMembersIndexRoute = ClubMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => ClubRoute,
} as any)
const AppTournamentsIndexRoute = AppTournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsIndexRoute = AppBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AppRoute,
} as any)
const AdminMembersIndexRoute = AdminMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => AdminRoute,
} as any)
const TournamentsTournamentIdLiveRoute =
  TournamentsTournamentIdLiveRouteImport.update({
    id: '/tournaments/$tournamentId/live',
    path: '/tournaments/$tournamentId/live',
    getParentRoute: () => rootRouteImport,
  } as any)
const GolferTournamentsTournamentIdRoute =
  GolferTournamentsTournamentIdRouteImport.update({
    id: '/tournaments/$tournamentId',
    path: '/tournaments/$tournamentId',
    getParentRoute: () => GolferRoute,
  } as any)
const GolferHistoryClubIdRoute = GolferHistoryClubIdRouteImport.update({
  id: '/history/$clubId',
  path: '/history/$clubId',
  getParentRoute: () => GolferRoute,
} as any)
const GolferCoursesCourseIdRoute = GolferCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => GolferRoute,
} as any)
const GolferBookingsBookingIdRoute = GolferBookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => GolferRoute,
} as any)
const GolferBookCourseIdRoute = GolferBookCourseIdRouteImport.update({
  id: '/book/$courseId',
  path: '/book/$courseId',
  getParentRoute: () => GolferRoute,
} as any)
const ClubMembersMemberIdRoute = ClubMembersMemberIdRouteImport.update({
  id: '/members/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => ClubRoute,
} as any)
const AppTournamentsTournamentIdRoute =
  AppTournamentsTournamentIdRouteImport.update({
    id: '/tournaments/$tournamentId',
    path: '/tournaments/$tournamentId',
    getParentRoute: () => AppRoute,
  } as any)
const AppHistoryClubIdRoute = AppHistoryClubIdRouteImport.update({
  id: '/history/$clubId',
  path: '/history/$clubId',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesCourseIdRoute = AppCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsBookingIdRoute = AppBookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => AppRoute,
} as any)
const AppBookCourseIdRoute = AppBookCourseIdRouteImport.update({
  id: '/book/$courseId',
  path: '/book/$courseId',
  getParentRoute: () => AppRoute,
} as any)
const AdminMembersUserIdRoute = AdminMembersUserIdRouteImport.update({
  id: '/members/$userId',
  path: '/members/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const GolferTournamentsTournamentIdScoreRoute =
  GolferTournamentsTournamentIdScoreRouteImport.update({
    id: '/score',
    path: '/score',
    getParentRoute: () => GolferTournamentsTournamentIdRoute,
  } as any)
const AppTournamentsTournamentIdScoreRoute =
  AppTournamentsTournamentIdScoreRouteImport.update({
    id: '/score',
    path: '/score',
    getParentRoute: () => AppTournamentsTournamentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/club': typeof ClubRouteWithChildren
  '/docs': typeof DocsRoute
  '/golfer': typeof GolferRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/apps': typeof AdminAppsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/club-admins': typeof AdminClubAdminsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/app/chat': typeof AppChatRoute
  '/app/login': typeof AppLoginRoute
  '/app/loyalty': typeof AppLoyaltyRoute
  '/app/profile': typeof AppProfileRoute
  '/app/scorecard': typeof AppScorecardRoute
  '/app/wallet': typeof AppWalletRoute
  '/club/analytics': typeof ClubAnalyticsRoute
  '/club/bookinglist': typeof ClubBookinglistRoute
  '/club/course-setup': typeof ClubCourseSetupRoute
  '/club/loyalty': typeof ClubLoyaltyRoute
  '/club/promotions': typeof ClubPromotionsRoute
  '/club/slots': typeof ClubSlotsRoute
  '/club/vouchers': typeof ClubVouchersRoute
  '/golfer/loyalty': typeof GolferLoyaltyRoute
  '/golfer/profile': typeof GolferProfileRoute
  '/golfer/scorecard': typeof GolferScorecardRoute
  '/golfer/wallet': typeof GolferWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/club/': typeof ClubIndexRoute
  '/golfer/': typeof GolferIndexRoute
  '/admin/members/$userId': typeof AdminMembersUserIdRoute
  '/app/book/$courseId': typeof AppBookCourseIdRoute
  '/app/bookings/$bookingId': typeof AppBookingsBookingIdRoute
  '/app/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/app/history/$clubId': typeof AppHistoryClubIdRoute
  '/app/tournaments/$tournamentId': typeof AppTournamentsTournamentIdRouteWithChildren
  '/club/members/$memberId': typeof ClubMembersMemberIdRoute
  '/golfer/book/$courseId': typeof GolferBookCourseIdRoute
  '/golfer/bookings/$bookingId': typeof GolferBookingsBookingIdRoute
  '/golfer/courses/$courseId': typeof GolferCoursesCourseIdRoute
  '/golfer/history/$clubId': typeof GolferHistoryClubIdRoute
  '/golfer/tournaments/$tournamentId': typeof GolferTournamentsTournamentIdRouteWithChildren
  '/tournaments/$tournamentId/live': typeof TournamentsTournamentIdLiveRoute
  '/admin/members/': typeof AdminMembersIndexRoute
  '/app/bookings/': typeof AppBookingsIndexRoute
  '/app/courses/': typeof AppCoursesIndexRoute
  '/app/tournaments/': typeof AppTournamentsIndexRoute
  '/club/members/': typeof ClubMembersIndexRoute
  '/golfer/bookings/': typeof GolferBookingsIndexRoute
  '/golfer/courses/': typeof GolferCoursesIndexRoute
  '/golfer/tournaments/': typeof GolferTournamentsIndexRoute
  '/app/tournaments/$tournamentId/score': typeof AppTournamentsTournamentIdScoreRoute
  '/golfer/tournaments/$tournamentId/score': typeof GolferTournamentsTournamentIdScoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/apps': typeof AdminAppsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/club-admins': typeof AdminClubAdminsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/app/chat': typeof AppChatRoute
  '/app/login': typeof AppLoginRoute
  '/app/loyalty': typeof AppLoyaltyRoute
  '/app/profile': typeof AppProfileRoute
  '/app/scorecard': typeof AppScorecardRoute
  '/app/wallet': typeof AppWalletRoute
  '/club/analytics': typeof ClubAnalyticsRoute
  '/club/bookinglist': typeof ClubBookinglistRoute
  '/club/course-setup': typeof ClubCourseSetupRoute
  '/club/loyalty': typeof ClubLoyaltyRoute
  '/club/promotions': typeof ClubPromotionsRoute
  '/club/slots': typeof ClubSlotsRoute
  '/club/vouchers': typeof ClubVouchersRoute
  '/golfer/loyalty': typeof GolferLoyaltyRoute
  '/golfer/profile': typeof GolferProfileRoute
  '/golfer/scorecard': typeof GolferScorecardRoute
  '/golfer/wallet': typeof GolferWalletRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/club': typeof ClubIndexRoute
  '/golfer': typeof GolferIndexRoute
  '/admin/members/$userId': typeof AdminMembersUserIdRoute
  '/app/book/$courseId': typeof AppBookCourseIdRoute
  '/app/bookings/$bookingId': typeof AppBookingsBookingIdRoute
  '/app/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/app/history/$clubId': typeof AppHistoryClubIdRoute
  '/app/tournaments/$tournamentId': typeof AppTournamentsTournamentIdRouteWithChildren
  '/club/members/$memberId': typeof ClubMembersMemberIdRoute
  '/golfer/book/$courseId': typeof GolferBookCourseIdRoute
  '/golfer/bookings/$bookingId': typeof GolferBookingsBookingIdRoute
  '/golfer/courses/$courseId': typeof GolferCoursesCourseIdRoute
  '/golfer/history/$clubId': typeof GolferHistoryClubIdRoute
  '/golfer/tournaments/$tournamentId': typeof GolferTournamentsTournamentIdRouteWithChildren
  '/tournaments/$tournamentId/live': typeof TournamentsTournamentIdLiveRoute
  '/admin/members': typeof AdminMembersIndexRoute
  '/app/bookings': typeof AppBookingsIndexRoute
  '/app/courses': typeof AppCoursesIndexRoute
  '/app/tournaments': typeof AppTournamentsIndexRoute
  '/club/members': typeof ClubMembersIndexRoute
  '/golfer/bookings': typeof GolferBookingsIndexRoute
  '/golfer/courses': typeof GolferCoursesIndexRoute
  '/golfer/tournaments': typeof GolferTournamentsIndexRoute
  '/app/tournaments/$tournamentId/score': typeof AppTournamentsTournamentIdScoreRoute
  '/golfer/tournaments/$tournamentId/score': typeof GolferTournamentsTournamentIdScoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/club': typeof ClubRouteWithChildren
  '/docs': typeof DocsRoute
  '/golfer': typeof GolferRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/apps': typeof AdminAppsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/club-admins': typeof AdminClubAdminsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/app/chat': typeof AppChatRoute
  '/app/login': typeof AppLoginRoute
  '/app/loyalty': typeof AppLoyaltyRoute
  '/app/profile': typeof AppProfileRoute
  '/app/scorecard': typeof AppScorecardRoute
  '/app/wallet': typeof AppWalletRoute
  '/club/analytics': typeof ClubAnalyticsRoute
  '/club/bookinglist': typeof ClubBookinglistRoute
  '/club/course-setup': typeof ClubCourseSetupRoute
  '/club/loyalty': typeof ClubLoyaltyRoute
  '/club/promotions': typeof ClubPromotionsRoute
  '/club/slots': typeof ClubSlotsRoute
  '/club/vouchers': typeof ClubVouchersRoute
  '/golfer/loyalty': typeof GolferLoyaltyRoute
  '/golfer/profile': typeof GolferProfileRoute
  '/golfer/scorecard': typeof GolferScorecardRoute
  '/golfer/wallet': typeof GolferWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/club/': typeof ClubIndexRoute
  '/golfer/': typeof GolferIndexRoute
  '/admin/members/$userId': typeof AdminMembersUserIdRoute
  '/app/book/$courseId': typeof AppBookCourseIdRoute
  '/app/bookings/$bookingId': typeof AppBookingsBookingIdRoute
  '/app/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/app/history/$clubId': typeof AppHistoryClubIdRoute
  '/app/tournaments/$tournamentId': typeof AppTournamentsTournamentIdRouteWithChildren
  '/club/members/$memberId': typeof ClubMembersMemberIdRoute
  '/golfer/book/$courseId': typeof GolferBookCourseIdRoute
  '/golfer/bookings/$bookingId': typeof GolferBookingsBookingIdRoute
  '/golfer/courses/$courseId': typeof GolferCoursesCourseIdRoute
  '/golfer/history/$clubId': typeof GolferHistoryClubIdRoute
  '/golfer/tournaments/$tournamentId': typeof GolferTournamentsTournamentIdRouteWithChildren
  '/tournaments/$tournamentId/live': typeof TournamentsTournamentIdLiveRoute
  '/admin/members/': typeof AdminMembersIndexRoute
  '/app/bookings/': typeof AppBookingsIndexRoute
  '/app/courses/': typeof AppCoursesIndexRoute
  '/app/tournaments/': typeof AppTournamentsIndexRoute
  '/club/members/': typeof ClubMembersIndexRoute
  '/golfer/bookings/': typeof GolferBookingsIndexRoute
  '/golfer/courses/': typeof GolferCoursesIndexRoute
  '/golfer/tournaments/': typeof GolferTournamentsIndexRoute
  '/app/tournaments/$tournamentId/score': typeof AppTournamentsTournamentIdScoreRoute
  '/golfer/tournaments/$tournamentId/score': typeof GolferTournamentsTournamentIdScoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/club'
    | '/docs'
    | '/golfer'
    | '/login'
    | '/admin/analytics'
    | '/admin/apps'
    | '/admin/audit'
    | '/admin/club-admins'
    | '/admin/courses'
    | '/admin/integrations'
    | '/app/chat'
    | '/app/login'
    | '/app/loyalty'
    | '/app/profile'
    | '/app/scorecard'
    | '/app/wallet'
    | '/club/analytics'
    | '/club/bookinglist'
    | '/club/course-setup'
    | '/club/loyalty'
    | '/club/promotions'
    | '/club/slots'
    | '/club/vouchers'
    | '/golfer/loyalty'
    | '/golfer/profile'
    | '/golfer/scorecard'
    | '/golfer/wallet'
    | '/admin/'
    | '/app/'
    | '/club/'
    | '/golfer/'
    | '/admin/members/$userId'
    | '/app/book/$courseId'
    | '/app/bookings/$bookingId'
    | '/app/courses/$courseId'
    | '/app/history/$clubId'
    | '/app/tournaments/$tournamentId'
    | '/club/members/$memberId'
    | '/golfer/book/$courseId'
    | '/golfer/bookings/$bookingId'
    | '/golfer/courses/$courseId'
    | '/golfer/history/$clubId'
    | '/golfer/tournaments/$tournamentId'
    | '/tournaments/$tournamentId/live'
    | '/admin/members/'
    | '/app/bookings/'
    | '/app/courses/'
    | '/app/tournaments/'
    | '/club/members/'
    | '/golfer/bookings/'
    | '/golfer/courses/'
    | '/golfer/tournaments/'
    | '/app/tournaments/$tournamentId/score'
    | '/golfer/tournaments/$tournamentId/score'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/login'
    | '/admin/analytics'
    | '/admin/apps'
    | '/admin/audit'
    | '/admin/club-admins'
    | '/admin/courses'
    | '/admin/integrations'
    | '/app/chat'
    | '/app/login'
    | '/app/loyalty'
    | '/app/profile'
    | '/app/scorecard'
    | '/app/wallet'
    | '/club/analytics'
    | '/club/bookinglist'
    | '/club/course-setup'
    | '/club/loyalty'
    | '/club/promotions'
    | '/club/slots'
    | '/club/vouchers'
    | '/golfer/loyalty'
    | '/golfer/profile'
    | '/golfer/scorecard'
    | '/golfer/wallet'
    | '/admin'
    | '/app'
    | '/club'
    | '/golfer'
    | '/admin/members/$userId'
    | '/app/book/$courseId'
    | '/app/bookings/$bookingId'
    | '/app/courses/$courseId'
    | '/app/history/$clubId'
    | '/app/tournaments/$tournamentId'
    | '/club/members/$memberId'
    | '/golfer/book/$courseId'
    | '/golfer/bookings/$bookingId'
    | '/golfer/courses/$courseId'
    | '/golfer/history/$clubId'
    | '/golfer/tournaments/$tournamentId'
    | '/tournaments/$tournamentId/live'
    | '/admin/members'
    | '/app/bookings'
    | '/app/courses'
    | '/app/tournaments'
    | '/club/members'
    | '/golfer/bookings'
    | '/golfer/courses'
    | '/golfer/tournaments'
    | '/app/tournaments/$tournamentId/score'
    | '/golfer/tournaments/$tournamentId/score'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/club'
    | '/docs'
    | '/golfer'
    | '/login'
    | '/admin/analytics'
    | '/admin/apps'
    | '/admin/audit'
    | '/admin/club-admins'
    | '/admin/courses'
    | '/admin/integrations'
    | '/app/chat'
    | '/app/login'
    | '/app/loyalty'
    | '/app/profile'
    | '/app/scorecard'
    | '/app/wallet'
    | '/club/analytics'
    | '/club/bookinglist'
    | '/club/course-setup'
    | '/club/loyalty'
    | '/club/promotions'
    | '/club/slots'
    | '/club/vouchers'
    | '/golfer/loyalty'
    | '/golfer/profile'
    | '/golfer/scorecard'
    | '/golfer/wallet'
    | '/admin/'
    | '/app/'
    | '/club/'
    | '/golfer/'
    | '/admin/members/$userId'
    | '/app/book/$courseId'
    | '/app/bookings/$bookingId'
    | '/app/courses/$courseId'
    | '/app/history/$clubId'
    | '/app/tournaments/$tournamentId'
    | '/club/members/$memberId'
    | '/golfer/book/$courseId'
    | '/golfer/bookings/$bookingId'
    | '/golfer/courses/$courseId'
    | '/golfer/history/$clubId'
    | '/golfer/tournaments/$tournamentId'
    | '/tournaments/$tournamentId/live'
    | '/admin/members/'
    | '/app/bookings/'
    | '/app/courses/'
    | '/app/tournaments/'
    | '/club/members/'
    | '/golfer/bookings/'
    | '/golfer/courses/'
    | '/golfer/tournaments/'
    | '/app/tournaments/$tournamentId/score'
    | '/golfer/tournaments/$tournamentId/score'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ClubRoute: typeof ClubRouteWithChildren
  DocsRoute: typeof DocsRoute
  GolferRoute: typeof GolferRouteWithChildren
  LoginRoute: typeof LoginRoute
  TournamentsTournamentIdLiveRoute: typeof TournamentsTournamentIdLiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golfer': {
      id: '/golfer'
      path: '/golfer'
      fullPath: '/golfer'
      preLoaderRoute: typeof GolferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golfer/': {
      id: '/golfer/'
      path: '/'
      fullPath: '/golfer/'
      preLoaderRoute: typeof GolferIndexRouteImport
      parentRoute: typeof GolferRoute
    }
    '/club/': {
      id: '/club/'
      path: '/'
      fullPath: '/club/'
      preLoaderRoute: typeof ClubIndexRouteImport
      parentRoute: typeof ClubRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/golfer/wallet': {
      id: '/golfer/wallet'
      path: '/wallet'
      fullPath: '/golfer/wallet'
      preLoaderRoute: typeof GolferWalletRouteImport
      parentRoute: typeof GolferRoute
    }
    '/golfer/scorecard': {
      id: '/golfer/scorecard'
      path: '/scorecard'
      fullPath: '/golfer/scorecard'
      preLoaderRoute: typeof GolferScorecardRouteImport
      parentRoute: typeof GolferRoute
    }
    '/golfer/profile': {
      id: '/golfer/profile'
      path: '/profile'
      fullPath: '/golfer/profile'
      preLoaderRoute: typeof GolferProfileRouteImport
      parentRoute: typeof GolferRoute
    }
    '/golfer/loyalty': {
      id: '/golfer/loyalty'
      path: '/loyalty'
      fullPath: '/golfer/loyalty'
      preLoaderRoute: typeof GolferLoyaltyRouteImport
      parentRoute: typeof GolferRoute
    }
    '/club/vouchers': {
      id: '/club/vouchers'
      path: '/vouchers'
      fullPath: '/club/vouchers'
      preLoaderRoute: typeof ClubVouchersRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/slots': {
      id: '/club/slots'
      path: '/slots'
      fullPath: '/club/slots'
      preLoaderRoute: typeof ClubSlotsRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/promotions': {
      id: '/club/promotions'
      path: '/promotions'
      fullPath: '/club/promotions'
      preLoaderRoute: typeof ClubPromotionsRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/loyalty': {
      id: '/club/loyalty'
      path: '/loyalty'
      fullPath: '/club/loyalty'
      preLoaderRoute: typeof ClubLoyaltyRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/course-setup': {
      id: '/club/course-setup'
      path: '/course-setup'
      fullPath: '/club/course-setup'
      preLoaderRoute: typeof ClubCourseSetupRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/bookinglist': {
      id: '/club/bookinglist'
      path: '/bookinglist'
      fullPath: '/club/bookinglist'
      preLoaderRoute: typeof ClubBookinglistRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/analytics': {
      id: '/club/analytics'
      path: '/analytics'
      fullPath: '/club/analytics'
      preLoaderRoute: typeof ClubAnalyticsRouteImport
      parentRoute: typeof ClubRoute
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scorecard': {
      id: '/app/scorecard'
      path: '/scorecard'
      fullPath: '/app/scorecard'
      preLoaderRoute: typeof AppScorecardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/loyalty': {
      id: '/app/loyalty'
      path: '/loyalty'
      fullPath: '/app/loyalty'
      preLoaderRoute: typeof AppLoyaltyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/club-admins': {
      id: '/admin/club-admins'
      path: '/club-admins'
      fullPath: '/admin/club-admins'
      preLoaderRoute: typeof AdminClubAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/apps': {
      id: '/admin/apps'
      path: '/apps'
      fullPath: '/admin/apps'
      preLoaderRoute: typeof AdminAppsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/golfer/tournaments/': {
      id: '/golfer/tournaments/'
      path: '/tournaments'
      fullPath: '/golfer/tournaments/'
      preLoaderRoute: typeof GolferTournamentsIndexRouteImport
      parentRoute: typeof GolferRoute
    }
    '/golfer/courses/': {
      id: '/golfer/courses/'
      path: '/courses'
      fullPath: '/golfer/courses/'
      preLoaderRoute: typeof GolferCoursesIndexRouteImport
      parentRoute: typeof GolferRoute
    }
    '/golfer/bookings/': {
      id: '/golfer/bookings/'
      path: '/bookings'
      fullPath: '/golfer/bookings/'
      preLoaderRoute: typeof GolferBookingsIndexRouteImport
      parentRoute: typeof GolferRoute
    }
    '/club/members/': {
      id: '/club/members/'
      path: '/members'
      fullPath: '/club/members/'
      preLoaderRoute: typeof ClubMembersIndexRouteImport
      parentRoute: typeof ClubRoute
    }
    '/app/tournaments/': {
      id: '/app/tournaments/'
      path: '/tournaments'
      fullPath: '/app/tournaments/'
      preLoaderRoute: typeof AppTournamentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courses/': {
      id: '/app/courses/'
      path: '/courses'
      fullPath: '/app/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings/': {
      id: '/app/bookings/'
      path: '/bookings'
      fullPath: '/app/bookings/'
      preLoaderRoute: typeof AppBookingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/members/': {
      id: '/admin/members/'
      path: '/members'
      fullPath: '/admin/members/'
      preLoaderRoute: typeof AdminMembersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tournaments/$tournamentId/live': {
      id: '/tournaments/$tournamentId/live'
      path: '/tournaments/$tournamentId/live'
      fullPath: '/tournaments/$tournamentId/live'
      preLoaderRoute: typeof TournamentsTournamentIdLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golfer/tournaments/$tournamentId': {
      id: '/golfer/tournaments/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/golfer/tournaments/$tournamentId'
      preLoaderRoute: typeof GolferTournamentsTournamentIdRouteImport
      parentRoute: typeof GolferRoute
    }
    '/golfer/history/$clubId': {
      id: '/golfer/history/$clubId'
      path: '/history/$clubId'
      fullPath: '/golfer/history/$clubId'
      preLoaderRoute: typeof GolferHistoryClubIdRouteImport
      parentRoute: typeof GolferRoute
    }
    '/golfer/courses/$courseId': {
      id: '/golfer/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/golfer/courses/$courseId'
      preLoaderRoute: typeof GolferCoursesCourseIdRouteImport
      parentRoute: typeof GolferRoute
    }
    '/golfer/bookings/$bookingId': {
      id: '/golfer/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/golfer/bookings/$bookingId'
      preLoaderRoute: typeof GolferBookingsBookingIdRouteImport
      parentRoute: typeof GolferRoute
    }
    '/golfer/book/$courseId': {
      id: '/golfer/book/$courseId'
      path: '/book/$courseId'
      fullPath: '/golfer/book/$courseId'
      preLoaderRoute: typeof GolferBookCourseIdRouteImport
      parentRoute: typeof GolferRoute
    }
    '/club/members/$memberId': {
      id: '/club/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/club/members/$memberId'
      preLoaderRoute: typeof ClubMembersMemberIdRouteImport
      parentRoute: typeof ClubRoute
    }
    '/app/tournaments/$tournamentId': {
      id: '/app/tournaments/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/app/tournaments/$tournamentId'
      preLoaderRoute: typeof AppTournamentsTournamentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history/$clubId': {
      id: '/app/history/$clubId'
      path: '/history/$clubId'
      fullPath: '/app/history/$clubId'
      preLoaderRoute: typeof AppHistoryClubIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courses/$courseId': {
      id: '/app/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/app/courses/$courseId'
      preLoaderRoute: typeof AppCoursesCourseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings/$bookingId': {
      id: '/app/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/app/bookings/$bookingId'
      preLoaderRoute: typeof AppBookingsBookingIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/book/$courseId': {
      id: '/app/book/$courseId'
      path: '/book/$courseId'
      fullPath: '/app/book/$courseId'
      preLoaderRoute: typeof AppBookCourseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/members/$userId': {
      id: '/admin/members/$userId'
      path: '/members/$userId'
      fullPath: '/admin/members/$userId'
      preLoaderRoute: typeof AdminMembersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/golfer/tournaments/$tournamentId/score': {
      id: '/golfer/tournaments/$tournamentId/score'
      path: '/score'
      fullPath: '/golfer/tournaments/$tournamentId/score'
      preLoaderRoute: typeof GolferTournamentsTournamentIdScoreRouteImport
      parentRoute: typeof GolferTournamentsTournamentIdRoute
    }
    '/app/tournaments/$tournamentId/score': {
      id: '/app/tournaments/$tournamentId/score'
      path: '/score'
      fullPath: '/app/tournaments/$tournamentId/score'
      preLoaderRoute: typeof AppTournamentsTournamentIdScoreRouteImport
      parentRoute: typeof AppTournamentsTournamentIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAppsRoute: typeof AdminAppsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminClubAdminsRoute: typeof AdminClubAdminsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminMembersUserIdRoute: typeof AdminMembersUserIdRoute
  AdminMembersIndexRoute: typeof AdminMembersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAppsRoute: AdminAppsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminClubAdminsRoute: AdminClubAdminsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminMembersUserIdRoute: AdminMembersUserIdRoute,
  AdminMembersIndexRoute: AdminMembersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppTournamentsTournamentIdRouteChildren {
  AppTournamentsTournamentIdScoreRoute: typeof AppTournamentsTournamentIdScoreRoute
}

const AppTournamentsTournamentIdRouteChildren: AppTournamentsTournamentIdRouteChildren =
  {
    AppTournamentsTournamentIdScoreRoute: AppTournamentsTournamentIdScoreRoute,
  }

const AppTournamentsTournamentIdRouteWithChildren =
  AppTournamentsTournamentIdRoute._addFileChildren(
    AppTournamentsTournamentIdRouteChildren,
  )

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppLoginRoute: typeof AppLoginRoute
  AppLoyaltyRoute: typeof AppLoyaltyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppScorecardRoute: typeof AppScorecardRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBookCourseIdRoute: typeof AppBookCourseIdRoute
  AppBookingsBookingIdRoute: typeof AppBookingsBookingIdRoute
  AppCoursesCourseIdRoute: typeof AppCoursesCourseIdRoute
  AppHistoryClubIdRoute: typeof AppHistoryClubIdRoute
  AppTournamentsTournamentIdRoute: typeof AppTournamentsTournamentIdRouteWithChildren
  AppBookingsIndexRoute: typeof AppBookingsIndexRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
  AppTournamentsIndexRoute: typeof AppTournamentsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppLoginRoute: AppLoginRoute,
  AppLoyaltyRoute: AppLoyaltyRoute,
  AppProfileRoute: AppProfileRoute,
  AppScorecardRoute: AppScorecardRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
  AppBookCourseIdRoute: AppBookCourseIdRoute,
  AppBookingsBookingIdRoute: AppBookingsBookingIdRoute,
  AppCoursesCourseIdRoute: AppCoursesCourseIdRoute,
  AppHistoryClubIdRoute: AppHistoryClubIdRoute,
  AppTournamentsTournamentIdRoute: AppTournamentsTournamentIdRouteWithChildren,
  AppBookingsIndexRoute: AppBookingsIndexRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
  AppTournamentsIndexRoute: AppTournamentsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ClubRouteChildren {
  ClubAnalyticsRoute: typeof ClubAnalyticsRoute
  ClubBookinglistRoute: typeof ClubBookinglistRoute
  ClubCourseSetupRoute: typeof ClubCourseSetupRoute
  ClubLoyaltyRoute: typeof ClubLoyaltyRoute
  ClubPromotionsRoute: typeof ClubPromotionsRoute
  ClubSlotsRoute: typeof ClubSlotsRoute
  ClubVouchersRoute: typeof ClubVouchersRoute
  ClubIndexRoute: typeof ClubIndexRoute
  ClubMembersMemberIdRoute: typeof ClubMembersMemberIdRoute
  ClubMembersIndexRoute: typeof ClubMembersIndexRoute
}

const ClubRouteChildren: ClubRouteChildren = {
  ClubAnalyticsRoute: ClubAnalyticsRoute,
  ClubBookinglistRoute: ClubBookinglistRoute,
  ClubCourseSetupRoute: ClubCourseSetupRoute,
  ClubLoyaltyRoute: ClubLoyaltyRoute,
  ClubPromotionsRoute: ClubPromotionsRoute,
  ClubSlotsRoute: ClubSlotsRoute,
  ClubVouchersRoute: ClubVouchersRoute,
  ClubIndexRoute: ClubIndexRoute,
  ClubMembersMemberIdRoute: ClubMembersMemberIdRoute,
  ClubMembersIndexRoute: ClubMembersIndexRoute,
}

const ClubRouteWithChildren = ClubRoute._addFileChildren(ClubRouteChildren)

interface GolferTournamentsTournamentIdRouteChildren {
  GolferTournamentsTournamentIdScoreRoute: typeof GolferTournamentsTournamentIdScoreRoute
}

const GolferTournamentsTournamentIdRouteChildren: GolferTournamentsTournamentIdRouteChildren =
  {
    GolferTournamentsTournamentIdScoreRoute:
      GolferTournamentsTournamentIdScoreRoute,
  }

const GolferTournamentsTournamentIdRouteWithChildren =
  GolferTournamentsTournamentIdRoute._addFileChildren(
    GolferTournamentsTournamentIdRouteChildren,
  )

interface GolferRouteChildren {
  GolferLoyaltyRoute: typeof GolferLoyaltyRoute
  GolferProfileRoute: typeof GolferProfileRoute
  GolferScorecardRoute: typeof GolferScorecardRoute
  GolferWalletRoute: typeof GolferWalletRoute
  GolferIndexRoute: typeof GolferIndexRoute
  GolferBookCourseIdRoute: typeof GolferBookCourseIdRoute
  GolferBookingsBookingIdRoute: typeof GolferBookingsBookingIdRoute
  GolferCoursesCourseIdRoute: typeof GolferCoursesCourseIdRoute
  GolferHistoryClubIdRoute: typeof GolferHistoryClubIdRoute
  GolferTournamentsTournamentIdRoute: typeof GolferTournamentsTournamentIdRouteWithChildren
  GolferBookingsIndexRoute: typeof GolferBookingsIndexRoute
  GolferCoursesIndexRoute: typeof GolferCoursesIndexRoute
  GolferTournamentsIndexRoute: typeof GolferTournamentsIndexRoute
}

const GolferRouteChildren: GolferRouteChildren = {
  GolferLoyaltyRoute: GolferLoyaltyRoute,
  GolferProfileRoute: GolferProfileRoute,
  GolferScorecardRoute: GolferScorecardRoute,
  GolferWalletRoute: GolferWalletRoute,
  GolferIndexRoute: GolferIndexRoute,
  GolferBookCourseIdRoute: GolferBookCourseIdRoute,
  GolferBookingsBookingIdRoute: GolferBookingsBookingIdRoute,
  GolferCoursesCourseIdRoute: GolferCoursesCourseIdRoute,
  GolferHistoryClubIdRoute: GolferHistoryClubIdRoute,
  GolferTournamentsTournamentIdRoute:
    GolferTournamentsTournamentIdRouteWithChildren,
  GolferBookingsIndexRoute: GolferBookingsIndexRoute,
  GolferCoursesIndexRoute: GolferCoursesIndexRoute,
  GolferTournamentsIndexRoute: GolferTournamentsIndexRoute,
}

const GolferRouteWithChildren =
  GolferRoute._addFileChildren(GolferRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ClubRoute: ClubRouteWithChildren,
  DocsRoute: DocsRoute,
  GolferRoute: GolferRouteWithChildren,
  LoginRoute: LoginRoute,
  TournamentsTournamentIdLiveRoute: TournamentsTournamentIdLiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
